### ISSUE TITLE
Recommended platform and release?

### ISSUE THREAD

**Issue by VonHirsch** [christopherkobayashi/netatalk-classic#19]
Hello, is there a certain platform and release you test with or recommend?  

For example:
- NetBSD 9.2
- OpenBSD 7.1
- Ubuntu 22.04
- Other?

Thanks for this project!!

**Comment by VonHirsch** [comment]
Thanks for the info.  I'm striking out with NetBSD, OpenBSD & Ubuntu 22.04 & 20.04 but I'm sure it's user error.  I launch atalkd and afpd with the most basic settings, but netstat shows nothing listening on 548.  There be dragons here! :)

**Comment by christopherkobayashi** [comment]
As @rdmark said, OpenBSD won't work.  NetBSD and reasonable versions of Linux only.

This version of netatalk does not support AppleTalk-over-TCP.  You won't see anything listening to a port -- netstat doesn't display AppleTalk information.

A rough AppleTalk analog to netstat (with a bit of nmap) is nbplkup.  Example:

```
(21:59:35 martok <~>) 0 $ nbplkup 
                         martok:AFPServer                          1.233:128
                         martok:netatalk                           1.233:4
                         martok:Workstation                        1.233:4
                         hermes:SNMP Agent                         65281.4:8
                         hermes:LaserWriter                        65281.4:158
                         hermes:HP LaserJet                        65281.4:157
```

ifconfig can be somewhat useful as well:

```
(22:07:31 martok <~>) 130 $ ifconfig
vioif0: flags=0x8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
        ec_capabilities=1<VLAN_MTU>
        ec_enabled=0
        address: 52:54:00:24:2e:ff
        inet 192.x/24 broadcast 192.x flags 0x0
        inet6 fe80::x flags 0x0 scopeid 0x1
        inet6 x flags 0x0
        inet6 x flags 0x40<AUTOCONF>
        atalk 1.233 phase 2 range 1 - 65534 broadcast 1.255
```

Look at the logs in /var/log/netatalk (and if that directory doesn't exist, create it).

That should get you started with troubleshooting.
