### ISSUE TITLE
Bring back systemd services

### ISSUE THREAD

**Issue by rdmark** [christopherkobayashi/netatalk-classic#3]
It seems the experimental systemd services configurations were deprecated at some point in this fork, and it would be nice to get it back and support added for managing atalk/papd/timelord/a2boot daemons.

The systemd services is the preferred way to [manage daemons in Debian](https://wiki.debian.org/systemd) and it would make netatalk-classic a fully fledged member of the ecosystem.

**Comment by christopherkobayashi** [comment]
$ ./configure --help | grep systemd
  --enable-systemd        use general systemd configuration

... and "configure --enable-systemd ${other_options} && make && make install" appears to do the right thing.

Closing, feel free to reopen with compile logs if this doesn't work for you.
